### ISSUE TITLE
advancedperipherals.madefor.cc not available

### ISSUE THREAD

**Issue by SirEndii** [SquidDev-CC/madefor.cc#39]
I made #38 almost a month ago, but it does not seem to be available

**Comment by SquidDev** [comment]
Are you sure that's not on your/Netlify's side? The DNS record resolves fine for me.

**Comment by SirEndii** [comment]
Works fine

https://docs.intelligence-modding.de

https://advancedperipherals.netlify.app/

**Comment by SirEndii** [comment]
![image](https://user-images.githubusercontent.com/67484093/196293219-230f476b-6bc7-42f4-a994-c77d84da0edb.png)

I know this is german, but I hope you can extract some information.

```NET::ERR_CERT_COMMON_NAME_INVALID

advancedperipherals.madefor.cc normally uses encryption to protect your data. This time, when Opera tried to visit advancedperipherals.madefor.cc, the website returned unusual and false identity information. This can happen when an attacker tries to impersonate advancedperipherals.madefor.cc; or a WiFi login screen dropped the connection. However, your data is safe as Opera has stopped the connection before any data exchange.

You cannot visit advancedperipherals.madefor.cc at the moment because the website uses HSTS. Network errors and attacks are usually transient. Therefore, the site will probably work again later.```

**Comment by SquidDev** [comment]
Have you registered this domain as a cname with Netlify?

**Comment by SirEndii** [comment]
![image](https://user-images.githubusercontent.com/67484093/196363503-c1ef403f-54a3-47a1-a9e8-a564ada5a91f.png)
Yessir

**Comment by SquidDev** [comment]
That looks like the CloudFlare dashboard, not Netlifly's. Have you definitely got `advanceperipherals.madefor.cc` listed under your [Custom Domains](https://docs.netlify.com/domains-https/custom-domains/) screen?

CCing @MCJack123 and @JeremyStarTM - they've actually used Netlify, so might have a better idea of what you're doing wrong.

**Comment by SirEndii** [comment]
I feel very stupid right now
Yeah I didn't add the domain to the Netlify dashboard and I completely forgot that
works now

**Comment by SquidDev** [comment]
Glad you've got it working :).
