### ISSUE TITLE
[Question] sub-Subdomains

### ISSUE THREAD

**Issue by Commandcracker** [SquidDev-CC/madefor.cc#42]
Is it possible to have subdomains like this:
docs.foo.madefor.cc
public-server.foo.madefor.cc

**Comment by SquidDev** [comment]
Hrm, I'd assume so, I haven't actually tested.

**Comment by tizu69** [comment]
not sure of the implementation here, but cloudflare doesn't allow subsubdomains unless you buy their $10/mo advanced cert manager thing.

**Comment by SquidDev** [comment]
We don't use CloudFlare.

**Comment by tizu69** [comment]
> We don't use CloudFlare.

welp sorry then, I thought I saw an issue mentioning cloudflare here.
