### ISSUE TITLE
Remove freax ?

### ISSUE THREAD

**Issue by Commandcracker** [SquidDev-CC/madefor.cc#53]
IDK what freax is or was, but the page is not available anymore.
I found his([JeremyStarTM](https://github.com/JeremyStarTM)) [new page](https://jstm.staropensource.de/), but it has no CC project on it.

**Comment by piprett** [comment]
cc @JeremyStarTM

**Comment by SquidDev** [comment]
There's several domains which are dead - the [lint command](https://github.com/SquidDev-CC/madefor.cc/blob/dev/dns/lint.py#L61) will pick them up. My policy here is to only remove them when there's a need.

**Comment by JeremyStarTM** [comment]
Hey. This is a project is am still working on but I'm rather slow at it. I actually didn't notice that the site is down. I will see what I can do in a few days.
